CREATE TABLE country (
id integer NOT NULL,
code character varying(3),
name character varying(64),
status character varying(10)
);

CREATE SEQUENCE seq_country;
ALTER TABLE country ALTER COLUMN id SET DEFAULT nextval('seq_country');


insert into country (code, name, status) values
('ID','Indonesia', 'ACTIVE'),
('DZ','Algeria', 'ACTIVE'),
('AL','Albania', 'ACTIVE'),
('AD','Andorra', 'ACTIVE'),
('AO','Angola', 'ACTIVE'),
('AI','Anguilla', 'ACTIVE'),
('AQ','Antarctica', 'ACTIVE'),
('AR','Argentina', 'ACTIVE'),
('AM','Armenia', 'ACTIVE'),
('AW','Aruba', 'ACTIVE'),
('AU','Australia', 'ACTIVE'),
('AT','Austria', 'ACTIVE'),
('BS','Bahamas', 'ACTIVE'),
('BH','Bahrain', 'ACTIVE'),
('BD','Bangladesh', 'ACTIVE'),
('BY','Belarus', 'ACTIVE'),
('BE','Belgium', 'ACTIVE'),
('BZ','Belize', 'ACTIVE'),
('BJ','Benin', 'ACTIVE'),
('BT','Bhutan', 'ACTIVE'),
('BO','Bolivia', 'ACTIVE'),
('BW','Botswana', 'ACTIVE'),
('BV','Bouvet Island', 'ACTIVE'),
('BR','Brazil', 'ACTIVE'),
('IO','British Indian Ocean Territory', 'ACTIVE'),
('BN','Brunei Darussalam', 'ACTIVE'),
('BG','Bulgaria', 'ACTIVE'),
('BI','Burundi', 'ACTIVE'),
('CI','Cote D Ivoire', 'ACTIVE'),
('KH','Cambodia', 'ACTIVE'),
('CA','Canada', 'ACTIVE'),
('CV','Cape Verde', 'ACTIVE'),
('KY','Cayman Islands', 'ACTIVE'),
('CL','Chile', 'ACTIVE'),
('CN','China', 'ACTIVE'),
('CX','Christmas Island', 'ACTIVE'),
('CC','Cocos (Keeling) Islands', 'ACTIVE'),
('CO','Colombia', 'ACTIVE'),
('CG','Congo', 'ACTIVE'),
('CK','Cook Islands', 'ACTIVE'),
('CR','Costa Rica', 'ACTIVE'),
('HR','Croatia (local name: Hrvatska)', 'ACTIVE'),
('CU','Cuba', 'ACTIVE'),
('CY','Cyprus', 'ACTIVE'),
('CZ','Czech Republic', 'ACTIVE'),
('DK','Denmark', 'ACTIVE'),
('DJ','Djibouti', 'ACTIVE'),
('DO','Dominican Republic', 'ACTIVE'),
('EC','Ecuador', 'ACTIVE'),
('EG','Egypt', 'ACTIVE'),
('ER','Eritrea', 'ACTIVE'),
('EE','Estonia', 'ACTIVE'),
('ET','Ethiopia', 'ACTIVE'),
('FO','Faroe Islands', 'ACTIVE'),
('FJ','Fiji', 'ACTIVE'),
('FI','Finland', 'ACTIVE'),
('FR','France', 'ACTIVE'),
('GF','French Guiana', 'ACTIVE'),
('PF','French Polynesia', 'ACTIVE'),
('GA','Gabon', 'ACTIVE'),
('GE','Georgia', 'ACTIVE'),
('DE','Germany', 'ACTIVE'),
('GH','Ghana', 'ACTIVE'),
('GR','Greece', 'ACTIVE'),
('GL','Greenland', 'ACTIVE'),
('GD','Grenada', 'ACTIVE'),
('GP','Guadeloupe', 'ACTIVE'),
('GT','Guatemala', 'ACTIVE'),
('GN','Guinea', 'ACTIVE'),
('GY','Guyana', 'ACTIVE'),
('HT','Haiti', 'ACTIVE'),
('HM','Heard And Mcdonald Islands', 'ACTIVE'),
('HN','Honduras', 'ACTIVE'),
('HK','Hong Kong', 'ACTIVE'),
('IS','Iceland', 'ACTIVE'),
('IN','India', 'ACTIVE'),
('IQ','Iraq', 'ACTIVE'),
('IE','Ireland', 'ACTIVE'),
('IL','Israel', 'ACTIVE'),
('IT','Italy', 'ACTIVE'),
('JM','Jamaica', 'ACTIVE'),
('JO','Jordan', 'ACTIVE'),
('KZ','Kazakhstan', 'ACTIVE'),
('KE','Kenya', 'ACTIVE'),
('KI','Kiribati', 'ACTIVE'),
('KR','Korea Republic Of', 'ACTIVE'),
('KW','Kuwait', 'ACTIVE'),
('KG','Kyrgyzstan', 'ACTIVE'),
('LV','Latvia', 'ACTIVE'),
('LB','Lebanon', 'ACTIVE'),
('LS','Lesotho', 'ACTIVE'),
('LR','Liberia', 'ACTIVE'),
('LY','Libyan Arab Jamahiriya', 'ACTIVE'),
('LI','Liechtenstein', 'ACTIVE'),
('LT','Lithuania', 'ACTIVE'),
('MO','Macau', 'ACTIVE'),
('MK','Macedonia', 'ACTIVE'),
('MG','Madagascar', 'ACTIVE'),
('MW','Malawi', 'ACTIVE'),
('MV','Maldives', 'ACTIVE'),
('ML','Mali', 'ACTIVE'),
('MT','Malta', 'ACTIVE'),
('MQ','Martinique', 'ACTIVE'),
('MR','Mauritania', 'ACTIVE'),
('MU','Mauritius', 'ACTIVE'),
('MX','Mexico', 'ACTIVE'),
('MC','Monaco', 'ACTIVE'),
('MS','Montserrat', 'ACTIVE'),
('MA','Morocco', 'ACTIVE'),
('MZ','Mozambique', 'ACTIVE'),
('NA','Namibia', 'ACTIVE'),
('NR','Nauru', 'ACTIVE'),
('NP','Nepal', 'ACTIVE'),
('AN','Netherlands Antilles', 'ACTIVE'),
('NC','New Caledonia', 'ACTIVE'),
('NZ','New Zealand', 'ACTIVE'),
('NI','Nicaragua', 'ACTIVE'),
('NG','Nigeria', 'ACTIVE'),
('NU','Niue', 'ACTIVE'),
('NF','Norfolk Island', 'ACTIVE'),
('NO','Norway', 'ACTIVE'),
('RE','Reunion', 'ACTIVE'),
('TP','East Timor', 'ACTIVE'),
('YU','Yugoslavia', 'ACTIVE'),
('AF','Afghanistan', 'ACTIVE'),
('AS','American Samoa', 'ACTIVE'),
('AG','Antigua And Barbuda', 'ACTIVE'),
('AZ','Azerbaijan', 'ACTIVE'),
('BB','Barbados', 'ACTIVE'),
('BM','Bermuda', 'ACTIVE'),
('BA','Bosnia And Herzegowina', 'ACTIVE'),
('BF','Burkina Faso', 'ACTIVE'),
('CM','Cameroon', 'ACTIVE'),
('CF','Central African Republic', 'ACTIVE'),
('TD','Chad', 'ACTIVE'),
('KM','Comoros', 'ACTIVE'),
('CD','Congo The Democratic Republic Of The', 'ACTIVE'),
('DM','Dominica', 'ACTIVE'),
('SV','El Salvador', 'ACTIVE'),
('GQ','Equatorial Guinea', 'ACTIVE'),
('FK','Falkland Islands (Malvinas)', 'ACTIVE'),
('TF','French Southern Territories', 'ACTIVE'),
('GM','Gambia', 'ACTIVE'),
('GI','Gibraltar', 'ACTIVE'),
('GU','Guam', 'ACTIVE'),
('GW','Guinea-Bissau', 'ACTIVE'),
('VA','Holy See (Vatican City State)', 'ACTIVE'),
('HU','Hungary', 'ACTIVE'),
('IR','Iran (Islamic Republic Of)', 'ACTIVE'),
('JP','Japan', 'ACTIVE'),
('TL','TIMOR-LESTE', 'ACTIVE'),
('KP','Korea Democratic Peoples Republic Of', 'ACTIVE'),
('LA','Lao Peoples Democratic Republic', 'ACTIVE'),
('LU','Luxembourg', 'ACTIVE'),
('MY','Malaysia', 'ACTIVE'),
('MH','Marshall Islands', 'ACTIVE'),
('YT','Mayotte', 'ACTIVE'),
('MN','Mongolia', 'ACTIVE'),
('MM','Myanmar', 'ACTIVE'),
('NL','Netherlands', 'ACTIVE'),
('NE','Niger', 'ACTIVE'),
('MP','Northern Mariana Islands', 'ACTIVE'),
('OM','Oman', 'ACTIVE'),
('PK','Pakistan', 'ACTIVE'),
('PW','Palau', 'ACTIVE'),
('PS','Palestinian Territory', 'ACTIVE'),
('PA','Panama', 'ACTIVE'),
('PG','Papua New Guinea', 'ACTIVE'),
('PY','Paraguay', 'ACTIVE'),
('PE','Peru', 'ACTIVE'),
('PH','Philippines', 'ACTIVE'),
('PN','Pitcairn', 'ACTIVE'),
('PL','Poland', 'ACTIVE'),
('PT','Portugal', 'ACTIVE'),
('PR','Puerto Rico', 'ACTIVE'),
('QA','Qatar', 'ACTIVE'),
('RO','Romania', 'ACTIVE'),
('RU','Russian Federation', 'ACTIVE'),
('RW','Rwanda', 'ACTIVE'),
('SH','St. Helena', 'ACTIVE'),
('KN','Saint Kitts And Nevis', 'ACTIVE'),
('LC','Saint Lucia', 'ACTIVE'),
('PM','St. Pierre And Miquelon', 'ACTIVE'),
('VC','Saint Vincent And The Grenadines', 'ACTIVE'),
('WS','Samoa', 'ACTIVE'),
('SM','San Marino', 'ACTIVE'),
('ST','Sao Tome And Principe', 'ACTIVE'),
('SA','Saudi Arabia', 'ACTIVE'),
('SN','Senegal', 'ACTIVE'),
('SC','Seychelles', 'ACTIVE'),
('SL','Sierra Leone', 'ACTIVE'),
('SG','Singapore', 'ACTIVE'),
('SK','Slovakia (Slovak Republic)', 'ACTIVE'),
('SI','Slovenia', 'ACTIVE'),
('SB','Solomon Islands', 'ACTIVE'),
('SO','Somalia', 'ACTIVE'),
('ZA','South Africa', 'ACTIVE'),
('GS','South Georgia And The South Sandwich Islands', 'ACTIVE'),
('ES','Spain', 'ACTIVE'),
('LK','Sri Lanka', 'ACTIVE'),
('SD','Sudan', 'ACTIVE'),
('SR','Suriname', 'ACTIVE'),
('SJ','Svalbard And Jan Mayen Islands', 'ACTIVE'),
('SZ','Swaziland', 'ACTIVE'),
('SE','Sweden', 'ACTIVE'),
('CH','Switzerland', 'ACTIVE'),
('SY','Syrian Arab Republic', 'ACTIVE'),
('TW','Taiwan', 'ACTIVE'),
('TJ','Tajikistan', 'ACTIVE'),
('TZ','Tanzania', 'ACTIVE'),
('TH','Thailand', 'ACTIVE'),
('TG','Togo', 'ACTIVE'),
('TK','Tokelau', 'ACTIVE'),
('TO','Tonga', 'ACTIVE'),
('TT','Trinidad And Tobago', 'ACTIVE'),
('TN','Tunisia', 'ACTIVE'),
('TR','Turkey', 'ACTIVE'),
('TM','Turkmenistan', 'ACTIVE'),
('TC','Turks And Caicos Islands', 'ACTIVE'),
('TV','Tuvalu', 'ACTIVE'),
('UG','Uganda', 'ACTIVE'),
('UA','Ukraine', 'ACTIVE'),
('AE','United Arab Emirates', 'ACTIVE'),
('GB','United Kingdom', 'ACTIVE'),
('US','United States', 'ACTIVE'),
('UM','United States Minor Outlying Islands', 'ACTIVE'),
('UY','Uruguay', 'ACTIVE'),
('UZ','Uzbekistan', 'ACTIVE'),
('VU','Vanuatu', 'ACTIVE'),
('VE','Venezuela', 'ACTIVE'),
('VN','Vietnam ', 'ACTIVE'),
('VG','Virgin Islands (British)', 'ACTIVE'),
('VI','Virgin Islands (U.S.)', 'ACTIVE'),
('WF','Wallis And Futuna Islands', 'ACTIVE'),
('EH','Western Sahara', 'ACTIVE'),
('YE','Yemen', 'ACTIVE'),
('ZM','Zambia', 'ACTIVE'),
('ZW','Zimbabwe', 'ACTIVE'),
('RS','SERBIA', 'ACTIVE'),
('EU','EUROPEAN UNION', 'ACTIVE'),
('ME','MONTENEGRO', 'ACTIVE'),
('MD','MOLDOVA, REPUBLIC OF', 'ACTIVE'),
('KS','KOSOVO, REPUBLIC OF', 'ACTIVE'),
('FM','MICRONESIA, FEDERATED STATES OF', 'ACTIVE'),
('IM','ISLE OF MAN', 'ACTIVE'),
('SS','SOUTH SUDAN', 'ACTIVE'),
('JE','JERSEY', 'ACTIVE');